data:
  data_directory: "./files/titanic_uc"
  batch_size: 16
  n_samples:
  ontology_file: "titanic_with_individual_cabins_by_side.ttl"
  feature_class_map: "mapping_titanic_with_individual_cabins_by_side.json"

model:
  name: "OntologyCommunityDetection"
  dropout: 0.0
  heads: 1

hyperparams:
  num_communities: 2
  lambda: 1.0

training:
  epochs: 300
  lr: 0.0001
  save_model: False

experiment:
  name: "exp1_community_gnn"
  interpretation_label: 0
  log_dir: "logs/"
  save_log: True
  save_dir: "checkpoints/"
  repeat_analysis: 10