data:
  data_directory: "./data/titanic"
  batch_size: 16
  n_samples:
  ontology_file: ".data/titanic/titanic_with_cabins.ttl"
  feature_class_map: "./data/titanic/mapping_titanic.json"

model:
  name: "OntologyCommunityDetection"
  dropout: 0.0
  heads: 1

hyperparams:
  num_communities: 3
  lambda: 1.0

training:
  epochs: 300
  lr: 0.0001
  save_model: False

experiment:
  name: "exp1_community_gnn"
  seed: 42
  log_dir: "logs/"
  save_log: False
  save_dir: "checkpoints/"
